import Head from "next/head";
import Parser from "rss-parser";
import {
  Card,
  CardActionArea,
  CardContent,
  CardHeader,
  CardMedia,
  Container,
  Grid,
  Paper,
  Typography,
} from "@mui/material";
import Footer from "../components/footer";

const Home = ({ feed }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container>
          <Typography variant="h1" color="text.primary" gutterBottom>
            Rob Cary
          </Typography>
          <Typography
            variant="subtitle1"
            color="text.secondary"
            gutterBottom
            paragraph
          >
            Something short and leading about the collection below—its contents,
            the creator, etc. Make it short and sweet, but not too short so
            folks don&apos;t simply skip over it entirely.
          </Typography>
          <Paper
            sx={{
              position: "relative",
              backgroundColor: "grey.800",
              color: "#fff",
              mb: 4,
              backgroundSize: "cover",
              backgroundRepeat: "no-repeat",
              backgroundPosition: "center",
              backgroundImage: `url(http://via.placeholder.com/640x360)`,
            }}
          >
            <img src="http://via.placeholder.com/640x360" />
          </Paper>
          <Grid container spacing={2}>
            <Grid item xs={12}>
              <Typography variant="h5" color="inherit" paragraph>
                Blog Posts
              </Typography>
            </Grid>
            {feed.map((item, index) => (
              <Grid item xs={3} key={index}>
                <Card>
                  <CardActionArea>
                    <CardMedia
                      component="img"
                      height="140"
                      image="https://i.imgur.com/30OI4fv.png"
                      alt="green iguana"
                    />
                    <CardHeader title={item.title} />
                    <CardContent>{item.contentSnippet}</CardContent>
                  </CardActionArea>
                </Card>
              </Grid>
            ))}
          </Grid>
        </Container>
      </main>
      <Footer title="Title" description="Description"></Footer>
    </div>
  );
};

Home.getInitialProps = async () => {
  const parser = new Parser();

  let feed = await parser.parseURL("https://shipshape.io/feed.xml");
  feed = feed.items.filter((item) =>
    item["content:encoded"].includes("Rob Cary")
  );

  return { feed };
};

export default Home;
